docs/docs/index.md
mkdocs.yml

added section for using docs and link to issue tracker
----
:books: Documentation preview :books:: https://griptape--2.org.readthedocs.build/en/2/

contributing to docs

---

docs/index.md

added more to the tools section of the landing page w/ links

tools section

---

docs/index.md

Here is one of many PRs incoming for improving the documentation. I hope this helps!
----
:books: Documentation preview :books:: https://griptape--19.org.readthedocs.build/en/19/

fix(docs): fix typo; improve wording

---

docs/griptape-tools/official-tools/aws-cli.md

----
:books: Documentation preview :books:: https://griptape--20.org.readthedocs.build/en/20/

docs: improve wording & structure

---

docs/griptape-tools/official-tools/pdf-reader.md

This documents the PDF Reader tool with a concrete example
----
:books: Documentation preview :books:: https://griptape--21.org.readthedocs.build/en/21/

docs: Document PDF Reader

---

docs/griptape-framework/index.md

according to PR https://github.com/griptape-ai/griptape/pull/67
----
:books: Documentation preview :books:: https://griptape--30.org.readthedocs.build/en/30/

add Azure OpenAI support remarks 

---

docs/examples/talk-to-redshift.md
docs/griptape-framework/data/sql-drivers.md

Adding docs for:
* AmazonRedshiftSqlDriver
* SnowflakeSqlDriver
* Updated example for talk_to_redshift
----
:books: Documentation preview :books:: https://griptape--38.org.readthedocs.build/en/38/

Adding docs for redshift and snowflake sql drivers

---

docs/examples/load-query-and-chat-marqo.md
docs/griptape-framework/data/vector-stores.md
mkdocs.yml

This pull request adds documentation for the accompanying MarqoVectorStoreDriver pull request in the main repository. 
https://github.com/griptape-ai/griptape/pull/97 
----
:books: Documentation preview :books:: https://griptape--36.org.readthedocs.build/en/36/

Documentation for Marqo Vector Store Driver

---

docs/examples/talk_to_text_gen.md

adding a working text gen example + description of usage.
----
:books: Documentation preview :books:: https://griptape--39.org.readthedocs.build/en/39/

add text gen example

---

docs/griptape-framework/tools/tool-memory.md

----
:books: Documentation preview :books:: https://griptape--41.org.readthedocs.build/en/41/

Fix import

---

docs/griptape-framework/index.md
docs/griptape-framework/structures/pipelines.md
docs/griptape-framework/structures/workflows.md

----
:books: Documentation preview :books:: https://griptape--50.org.readthedocs.build/en/50/

Fix docs to reflect input -> parent_output rename

---

docs/griptape-framework/structures/conversation-memory.md

----
:books: Documentation preview :books:: https://griptape--53.org.readthedocs.build/en/53/

Add missing imports

---

docs/griptape-framework/tools/custom-tools.md

----
:books: Documentation preview :books:: https://griptape--54.org.readthedocs.build/en/54/

Fix imports on custom tools

---

docs/griptape-framework/data/loaders.md

----
:books: Documentation preview :books:: https://griptape--49.org.readthedocs.build/en/49/

Add docs for CsvLoader

---

docs/griptape-framework/data/loaders.md

----
:books: Documentation preview :books:: https://griptape--57.org.readthedocs.build/en/57/

Fix imports, arguments for loaders

---

docs/griptape-framework/data/query-engines.md

----
:books: Documentation preview :books:: https://griptape--58.org.readthedocs.build/en/58/

Add missing imports, fix upsert method

---

docs/griptape-framework/data/sql-drivers.md

----
:books: Documentation preview :books:: https://griptape--59.org.readthedocs.build/en/59/

Fix import for sql drivers

---

docs/griptape-framework/data/vector-stores.md

----
:books: Documentation preview :books:: https://griptape--60.org.readthedocs.build/en/60/

OpenSearch and updated Redis docs

---

docs/examples/talk-to-redshift.md

----
:books: Documentation preview :books:: https://griptape--61.org.readthedocs.build/en/61/

Remove unused import, fix syntax error

---

docs/examples/using-text-generation-web-ui.md

----
:books: Documentation preview :books:: https://griptape--62.org.readthedocs.build/en/62/

Fix markdown language hint

---

docs/griptape-tools/index.md

----
:books: Documentation preview :books:: https://griptape--63.org.readthedocs.build/en/63/

Fix imports

---

docs/griptape-tools/official-tools/aws-iam-client.md
docs/griptape-tools/official-tools/aws-s3-client.md
docs/griptape-tools/official-tools/calculator.md
docs/griptape-tools/official-tools/computer.md
docs/griptape-tools/official-tools/date-time.md
docs/griptape-tools/official-tools/email-client.md
docs/griptape-tools/official-tools/file-manager.md
docs/griptape-tools/official-tools/sql-client.md
docs/griptape-tools/official-tools/tool-output-processor.md
docs/griptape-tools/official-tools/vector-store-client.md
docs/griptape-tools/official-tools/web-scraper.md
docs/griptape-tools/official-tools/web-search.md

----
:books: Documentation preview :books:: https://griptape--64.org.readthedocs.build/en/64/

Fix official tools docs

---

docs/examples/store-conversation-memory-in-dynamodb.md

----
:books: Documentation preview :books:: https://griptape--66.org.readthedocs.build/en/66/

Update dynamodb conversation driver example

---

docs/griptape-framework/data/sql-drivers.md

----
:books: Documentation preview :books:: https://griptape--67.org.readthedocs.build/en/67/

Fix redshift driver docs

---

docs/examples/load-and-query-pinecone.md
docs/examples/load-query-and-chat-marqo.md
docs/examples/store-conversation-memory-in-dynamodb.md
docs/examples/using-text-generation-web-ui.md

----
:books: Documentation preview :books:: https://griptape--68.org.readthedocs.build/en/68/

Fix examples

---

docs/griptape-framework/data/sql-drivers.md

----
:books: Documentation preview :books:: https://griptape--70.org.readthedocs.build/en/70/

Update snowflake docs

---

docs/griptape-framework/data/vector-stores.md

----
:books: Documentation preview :books:: https://griptape--69.org.readthedocs.build/en/69/

Fix vector store docs

---

docs/griptape-framework/data/embedding-drivers.md
docs/griptape-framework/structures/prompt-drivers.md
docs/griptape-tools/official-tools/email-client.md
docs/griptape-tools/official-tools/rest-api-client.md
docs/griptape-tools/official-tools/vector-store-client.md

Requires https://github.com/griptape-ai/griptape/pull/212 to be deployed first.

Remove reference tables with links to reference

---

docs/contributing.md

----
:books: Documentation preview :books:: https://griptape--81.org.readthedocs.build/en/81/

Update contributing to reflect reference docs changes

---

.github/workflows/pull-request-links.yml
docs/griptape-framework/structures/agents.md

----
:books: Documentation preview :books:: https://griptape--100.org.readthedocs.build/

Fix preview link

---

docs/griptape-framework/structures/prompt-drivers.md
docs/griptape-tools/official-tools/google-drive-client.md
mkdocs.yml

Related to #110
----
:books: Documentation preview :books:: https://griptape--109.org.readthedocs.build/en/109/

New Google Tools Documentation 

---

docs/griptape-framework/data/embedding-drivers.md

----
:books: Documentation preview :books:: https://griptape--108.org.readthedocs.build/en/108/

Update embeddings docs

---

docs/griptape-tools/official-tools/google-cal-client.md
docs/griptape-tools/official-tools/google-gmail-client.md

Resolves #115 
Do not merge docs until Framework PR #323 is merged.
----
:books: Documentation preview :books:: https://griptape--116.org.readthedocs.build/

Documentation for user versions of GoogleCalenderClient and GoogleGmailClient

---

docs/griptape-framework/structures/prompt-drivers.md

----
:books: Documentation preview :books:: https://griptape--117.org.readthedocs.build/

Update bedrock default models

---

docs/griptape-framework/data/embedding-drivers.md
docs/griptape-framework/tools/tool-memory.md
docs/griptape-tools/official-tools/aws-s3-client.md
docs/griptape-tools/official-tools/tool-output-processor.md

----
:books: Documentation preview :books:: https://griptape--119.org.readthedocs.build/

Update tool memory examples

---

docs/griptape-tools/official-tools/google-docs-client.md
mkdocs.yml

Resolves #114 
----
:books: Documentation preview :books:: https://griptape--120.org.readthedocs.build/

GoogleDocsClient Documentation

---

docs/griptape-framework/structures/conversation-memory.md

Related to https://github.com/griptape-ai/griptape/issues/344
----
:books: Documentation preview :books:: https://griptape--122.org.readthedocs.build/

Update conversation memory docs

---

docs/griptape-framework/data/artifacts.md
docs/griptape-framework/data/vector-store-drivers.md
docs/griptape-framework/index.md
docs/griptape-framework/structures/conversation-memory.md
docs/griptape-framework/structures/tasks.md
docs/griptape-framework/tools/index.md
docs/griptape-framework/tools/tool-memory.md
docs/griptape-tools/official-tools/aws-iam-client.md
docs/griptape-tools/official-tools/aws-s3-client.md
docs/griptape-tools/official-tools/computer.md
docs/griptape-tools/official-tools/google-cal-client.md
docs/griptape-tools/official-tools/proxycurl-client.md
docs/griptape-tools/official-tools/sql-client.md
docs/griptape-tools/official-tools/web-scraper.md

----
:books: Documentation preview :books:: https://griptape--129.org.readthedocs.build/

Update docs with ToolMemory

---

.github/workflows/integration-tests.yml
docs/griptape-tools/official-tools/openweather-client.md
mkdocs.yml

Closes #92 
----
:books: Documentation preview :books:: https://griptape--121.org.readthedocs.build/

Add docs for OpenWeatherClient

---

docs/griptape-framework/structures/prompt-drivers.md

----
:books: Documentation preview :books:: https://griptape--128.org.readthedocs.build/

Fix comment

---

docs/griptape-framework/data/extraction-engines.md
mkdocs.yml

Resolves #103 
----
:books: Documentation preview :books:: https://griptape--130.org.readthedocs.build/

Documentation for Extraction Engines

---

docs/griptape-framework/structures/events.md

----
:books: Documentation preview :books:: https://griptape--112.org.readthedocs.build/

Add docs for streaming

---

docs/griptape-framework/structures/events.md

Docs for https://github.com/griptape-ai/griptape/pull/375
----
:books: Documentation preview :books:: https://griptape--132.org.readthedocs.build/

Update events to use new structure

---

docs/griptape-framework/structures/tasks.md

Resolves #101 
----
:books: Documentation preview :books:: https://griptape--127.org.readthedocs.build/

Missing Tasks Documentation

---

docs/griptape-tools/official-tools/text-memory-client.md

----
:books: Documentation preview :books:: https://dev-griptape-docs--150.org.readthedocs.build/

Update TextMemoryClient doc

---

docs/griptape-framework/structures/prompt-drivers.md

Relates to https://github.com/griptape-ai/griptape/pull/422
----
:books: Documentation preview :books:: https://griptape--142.org.readthedocs.build/

Update docs for openai updates

---

docs/griptape-framework/structures/workflows.md

Docs for https://github.com/griptape-ai/griptape/pull/429
----
:books: Documentation preview :books:: https://griptape--149.org.readthedocs.build/

Update Docs For New Workflow Syntax

---

docs/griptape-framework/data/sql-drivers.md
docs/griptape-framework/data/vector-store-drivers.md
docs/griptape-framework/index.md
docs/griptape-framework/structures/conversation-memory.md
docs/griptape-framework/structures/prompt-drivers.md

----
:books: Documentation preview :books:: https://dev-griptape-docs--146.org.readthedocs.build/

Optional deps

---

docs/griptape-framework/index.md
docs/griptape-framework/structures/conversation-memory.md
docs/griptape-tools/official-tools/rest-api-client.md

----
:books: Documentation preview :books:: https://dev-griptape-docs--151.org.readthedocs.build/

Update conversation_memory examples

---

docs/griptape-framework/index.md

----
:books: Documentation preview :books:: https://dev-griptape-docs--153.org.readthedocs.build/

Add note pointing towards all extras

---

docs/griptape-framework/structures/conversation-memory.md
docs/griptape-framework/structures/prompt-drivers.md
docs/griptape-framework/tools/task-memory.md
docs/griptape-tools/index.md
docs/griptape-tools/official-tools/proxycurl-client.md
docs/griptape-tools/official-tools/vector-store-client.md
tests/integration/test_code_snippets.py

----
:books: Documentation preview :books:: https://dev-griptape-docs--156.org.readthedocs.build/

Fix Docs for Integration Tests

---

docs/griptape-framework/data/embedding-drivers.md

----
:books: Documentation preview :books:: https://griptape--176.org.readthedocs.build/en/176/

Fix example

---

docs/griptape-framework/structures/events.md

Docs for https://github.com/griptape-ai/griptape/pull/478
----
:books: Documentation preview :books:: https://griptape--175.org.readthedocs.build/en/175/

Add docs for inspecting prompt events

---

docs/griptape-framework/data/embedding-drivers.md

----
📚 Documentation preview 📚: https://griptape--184.org.readthedocs.build/en/184/

Fix reference link

---

docs/griptape-cloud/getting-started/quickstart-cli.md

----
📚 Documentation preview 📚: https://griptape--189.org.readthedocs.build/en/189/

Update CLI new app command and directory path

---

docs/griptape-framework/data/embedding-drivers.md

Docs for https://github.com/griptape-ai/griptape/pull/498
----
📚 Documentation preview 📚: https://griptape--180.org.readthedocs.build/en/180/

Add SageMaker Embedding Driver docs

---

docs/griptape-framework/data/image-generation-engines.md
docs/griptape-framework/data/loaders.md
docs/griptape-tools/official-tools/inpainting-image-generation-client.md
docs/griptape-tools/official-tools/outpainting-image-generation-client.md
mkdocs.yml

----
📚 Documentation preview 📚: https://griptape--195.org.readthedocs.build/en/195/

Fix integration tests

---

docs/griptape-framework/data/embedding-drivers.md
docs/griptape-framework/structures/prompt-drivers.md
docs/griptape-tools/custom-tools/index.md
docs/griptape-tools/index.md

Closes #200 
----
📚 Documentation preview 📚: https://griptape--201.org.readthedocs.build/en/201/

Remove Ignore Annotation

---

docs/griptape-framework/structures/image-generation-drivers.md

Update Titan example to use Titan model

---

.github/workflows/pull-request-links.yml
docs/examples/multiple-agent-shared-memory.md
docs/griptape-framework/data/vector-store-drivers.md
mkdocs.yml

also fixing github action for docs preview link
----
📚 Documentation preview 📚: https://griptape--202.org.readthedocs.build//202/

Multi-agent shared vector database

---

docs/griptape-framework/data/image-generation-engines.md
docs/griptape-framework/data/loaders.md
docs/griptape-framework/structures/tasks.md

Depends on griptape-ai/griptape#618

Update ImageLoader interface in examples

---

docs/griptape-framework/data/vector-store-drivers.md

----
📚 Documentation preview 📚: https://griptape--209.org.readthedocs.build//209/

Add example mappings for Amazon OpenSearch index creation

---

docs/griptape-framework/structures/conversation-memory.md
docs/griptape-framework/tools/index.md
mkdocs.yml

----
📚 Documentation preview 📚: https://griptape--211.org.readthedocs.build//211/

Refactor header structure, fix a couple headings

---

docs/examples/load-query-and-chat-marqo.md

----
📚 Documentation preview 📚: https://griptape--214.org.readthedocs.build//214/

Fix marqo query example

---

docs/griptape-framework/data/loaders.md

Docs for https://github.com/griptape-ai/griptape/pull/624
----
📚 Documentation preview 📚: https://griptape--210.org.readthedocs.build//210/

Update docs for loader extras

---

.github/workflows/integration-tests.yml
docs/griptape-framework/drivers/embedding-drivers.md
poetry.lock

Docs for https://github.com/griptape-ai/griptape/pull/701
----
📚 Documentation preview 📚: https://griptape--230.org.readthedocs.build//230/

Add docs for voyageai

---

docs/griptape-framework/drivers/prompt-drivers.md
docs/griptape-framework/structures/config.md
poetry.lock

Docs for https://github.com/griptape-ai/griptape/pull/694
----
📚 Documentation preview 📚: https://griptape--229.org.readthedocs.build//229/

Update docs for Anthropic
