griptape-ai/griptape-docs

README.md, docs/griptape-framework/index.md
----
:books: Documentation preview :books:: https://griptape--32.org.readthedocs.build/en/32/
=> Fixing typos in Griptape Docs

docs/griptape-tools/official-tools/rest-api-client.md
The output of the get posts example is large enough to require using tool memory.
----
:books: Documentation preview :books:: https://griptape--35.org.readthedocs.build/en/35/
=> Update rest api docs to use tool memory, improve prompts

mkdocs.yml
In a recent commit examples/text-generation-web-ui.md was renamed to talk-to-text-gen.md but this change wasn't reflected in mkdocs.yml.
Renaming the file corrected the problem, I built the docs locally and validated the change worked correctly:
=> FIX 404 ERROR FOR Text Generation Web UI

docs/griptape-framework/structures/events.md
Fixed a bug in the handler function in events documentation where it called `e` instead of `event`.
----
:books: Documentation preview :books:: https://griptape--46.org.readthedocs.build/en/46/
=> fixed handler function to use event instead of e

docs/griptape-framework/structures/workflows.md
----
:books: Documentation preview :books:: https://griptape--51.org.readthedocs.build/en/51/
=> Add missing imports to workflow example

docs/griptape-framework/structures/prompt-drivers.md
Not sure if these are really "missing" imports since they're pretty small code snippets. Maybe they're not intended to be copy-pasted and run from the docs. In any case, I don't think it hurts to have the imports.
----
:books: Documentation preview :books:: https://griptape--52.org.readthedocs.build/en/52/
=> Add missing imports

docs/griptape-framework/data/embeddings.md
----
:books: Documentation preview :books:: https://griptape--56.org.readthedocs.build/en/56/
=> Remove extra newline below imports

docs/gen_ref_pages.py
Fixes `SUMMARY.md` appearing in search results.
----
:books: Documentation preview :books:: https://griptape--82.org.readthedocs.build/en/82/
=> Fix search exclusion in reference pages

docs/griptape-framework/data/chunkers.md, docs/griptape-framework/data/embedding-drivers.md, docs/griptape-framework/data/loaders.md, docs/griptape-framework/data/query-engines.md, docs/griptape-framework/data/summary-engines.md, tests/integration/test_repl_snippets.py
I'm removing the REPL snippets because they:
1. Broke the integration tests because the code snippets were technically no longer valid python (`>>>` characters).
2. Made copying the examples cumbersome because the copy button included `>>>` characters.
We could add print back to these examples, but many of them output _a lot_ of text, so printing to stdout isn't really that useful IMO.
----
:books: Documentation preview :books:: https://griptape--83.org.readthedocs.build/en/83/
=> Remove REPL snippets

docs/griptape-framework/data/loaders.md, docs/griptape-framework/data/sql-drivers.md, docs/griptape-framework/data/vector-store-drivers.md
Moves reference info into docstrings here: https://github.com/griptape-ai/griptape/pull/232.
Also fixes various formatting issues.
----
:books: Documentation preview :books:: https://griptape--89.org.readthedocs.build/en/89/
=> Move info to reference docstrings

docs/griptape-framework/data/vector-store-drivers.md
This PR updates the documentation to include a basic working example for using the PGVector vector store driver. Other vector store driver examples have been updated to include explicitly creating and setting the embedding driver as is now required. 
----
:books: Documentation preview :books:: https://griptape--106.org.readthedocs.build/
=> Add examples for PGVector vector store driver

docs/contributing.md
----
:books: Documentation preview :books:: https://griptape--131.org.readthedocs.build/
=> Contributing page had a typo 

docs/griptape-framework/data/chunkers.md
----
:books: Documentation preview :books:: https://griptape--134.org.readthedocs.build/
=> docs: adding missing model to tokenizer

docs/contributing.md
Relates to https://github.com/griptape-ai/griptape/pull/394v
----
:books: Documentation preview :books:: https://griptape--133.org.readthedocs.build/
=> Update contributing guidelines to match main repo

docs/griptape-framework/structures/workflows.md
Relates to https://github.com/griptape-ai/griptape/pull/410
----
:books: Documentation preview :books:: https://griptape--141.org.readthedocs.build/
=> Update workflow example

docs/griptape-framework/structures/conversation-memory.md
Docs for https://github.com/griptape-ai/griptape/pull/428
----
:books: Documentation preview :books:: https://griptape--144.org.readthedocs.build/
=> Remove warning about workflows missing conversation memory

docs/griptape-framework/data/artifacts.md, docs/griptape-framework/tools/task-memory.md, docs/griptape-tools/official-tools/vector-store-client.md
----
:books: Documentation preview :books:: https://griptape--164.org.readthedocs.build/en/164/
=> Fix missing references to tool memory

docs/griptape-framework/structures/workflows.md
The workflow story generation example uses insert_tasks but does not set `preserve_relationship=True`. As a result, the output of the `world_task` is not available to `story_task`. This updates the example to set the flag and maintain the relationship so the output is available for `story_task`.
----
:books: Documentation preview :books:: https://griptape--168.org.readthedocs.build/en/168/
=> Fix workflow example

docs/griptape-framework/structures/prompt-drivers.md
Adds a warning to the Prompt Drivers page indicating that a developer should be careful about selecting corresponding Prompt Driver and Embedding Driver pairs. This should be temporary until a more robust defaults management solution is implemented.
Related to griptape-ai/griptape#471
=> Add note about configuring corresponding prompt drivers and embedding drivers

docs/griptape-framework/data/embedding-drivers.md
Docs for https://github.com/griptape-ai/griptape/pull/499
----
📚 Documentation preview 📚: https://griptape--181.org.readthedocs.build/en/181/
=> Rename BedrockEmbeddingDriver to AmazonBedrockTitanEmbeddingDriver

docs/griptape-framework/structures/tasks.md
Docs for `CodeExecutingTask`. Used a pipeline with a basic character counting function for the example.
----
📚 Documentation preview 📚: https://griptape--192.org.readthedocs.build/en/192/
=> Code Execution Task Docs

docs/assets/css/extra.css, docs/griptape-framework/drivers/embedding-drivers.md, docs/griptape-framework/drivers/prompt-drivers.md, docs/griptape-tools/custom-tools/index.md, docs/griptape-tools/index.md, tests/integration/utils/code_blocks.py
`title` is the only valid text we can put after a code block language and still have it render. Since we're not using this field, we can stick some data in it and hide it with css.
----
📚 Documentation preview 📚: https://griptape--216.org.readthedocs.build//216/
=> Hack to exclude code snippets from pytest

.readthedocs.yml
Update to add virtualenv path env var to poetry install command.
=> Update readthedocs build config

docs/griptape-framework/data/chunkers.md, docs/griptape-framework/misc/tokenizers.md
Depends on griptape-ai/griptape#620
----
📚 Documentation preview 📚: https://griptape--212.org.readthedocs.build//212/
=> Remove references to default Tokenizer models
